all:
  children:
    debian:
      hosts:
        192.168.0.20:
          http_port: 8080
          https_port: 443
    redhat:
      hosts:     
        192.168.0.18:
          squid_port: 3128
      vars:
        ansible_port: 22
        ansible_ssh_user: fernandostn
