---
- hosts: redhat
  tasks:
    - name: Instalacao do nginx
      yum:
        name: nginx
        state: latest
      notify:
        - stop apache
        - restart nginx

  handlers:
    - name: stop apache
      systemd:
        name: httpd
        state: stop

    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
...