---

# Gerenciamento de pacotes e atualização do Sistema Operacional

- name: Atualizacao do Sistema Operacional
  yum: name=* state=latest update_cache=yes

- name: Instalacao de pacotes
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - net-tools
      - vim
      - nmap

# Configuração de Timezone

- name: Configurando timezone
  file: src=/usr/share/zoneinfo/America/Sao_Paulo dest=/etc/localtime state=link force=yes

# Copia de arquivos

- name: Copiando arquivo de backup
  copy: src=backup.tar.xz dest=/tmp/backup.tar.xz

# Configuracao do  motd

- name: Configurando motd
  template: src=motd dest=/etc/motd force=yes owner=root group=root

# Instalacao do Nginx

- name: Instalação do Nginx
  yum:
    name: nginx
    state: latest
  notify: Restart nginx
...
